stages:
  - test
  - build

variables:
  GIT_STRATEGY: clone


.test: &test
  stage: test
  script:
    - python -m pip install git+https://github.com/usnistgov/NEMO.git@8.1.0.dev
    - python -m pip install .
    - python ./run_tests.py

.test-ce: &test-ce
  stage: test
  script:
    - echo 'INSTALLED_APPS += ["NEMO.apps.nemo_ce"]' >> NEMO_online_training/tests/test_settings.py
    - python -m pip install .["NEMO-CE"]
    - python ./run_tests.py


Test NEMO python 3.10:
  <<: *test
  image: python:3.10

Test NEMO python 3.11:
  <<: *test
  image: python:3.11

Test NEMO python 3.12:
  <<: *test
  image: python:3.12

Test NEMO python 3.13:
  <<: *test
  image: python:3.13

Test NEMO-CE python 3.10:
  <<: *test-ce
  image: python:3.10

Test NEMO-CE python 3.11:
  <<: *test-ce
  image: python:3.11

Test NEMO-CE python 3.12:
  <<: *test-ce
  image: python:3.12

Test NEMO-CE python 3.13:
  <<: *test-ce
  image: python:3.13

Build Package:
  image: python:3
  stage: build
  script:
    - sed -i "s/^version =.*/version = '$(git describe --tags --abbrev=0).dev0'/" pyproject.toml
    - pip install --upgrade pip build
    - python -m build
  only:
    refs:
      - $CI_DEFAULT_BRANCH
      - tags

Release to PyPI:
  image: python:3
  stage: build
  script:
    - sed -i "s/^version =.*/version = '$(git describe --tags)'/" pyproject.toml
    - pip install --upgrade pip build twine
    - python -m build
    - twine upload --user $PYPI_USER --password $PYPI_PASSWORD ./dist/nemo_online_training*
  only:
    - tags