# Generated by Django 4.2.29 on 2026-03-31 01:45

import NEMO_online_training.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0144_alter_tool__adjustment_request_reviewers_and_more"),
        ("NEMO_online_training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlinetraining",
            name="default_due_date_days",
            field=models.PositiveIntegerField(
                default=30, help_text="The default number of days before this training is due"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="onlinetraining",
            name="user_filter",
            field=NEMO_online_training.fields.UserTypeFilterField(
                default="all_nemo,prospective",
                help_text="Select which users this training should be available to. You can select 'All NEMO users', new users (without NEMO accounts), and/or specific user types.",
            ),
        ),
        migrations.AddField(
            model_name="prospectiveuser",
            name="_user_type",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="NEMO.usertype"
            ),
        ),
    ]
