# Generated by Django 4.2.29 on 2026-04-16 18:29

import NEMO_online_training.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0144_alter_tool__adjustment_request_reviewers_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("NEMO_online_training", "0002_onlinetraining_default_due_date_days_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProspectiveUser",
            new_name="TrainingUser",
        ),
        migrations.RenameField(
            model_name="onlineusertraining",
            old_name="prospective_user",
            new_name="training_user",
        ),
        migrations.AlterField(
            model_name="onlinetraining",
            name="user_filter",
            field=NEMO_online_training.fields.UserTypeFilterField(
                default="all_nemo_users,all_new_users",
                help_text="Select which users this training should be available to. You can select 'All NEMO users', 'All new users' (without NEMO accounts), and/or specific user types.",
            ),
        ),
        migrations.AlterField(
            model_name="onlinetrainingaction",
            name="user_filter",
            field=NEMO_online_training.fields.UserTypeFilterField(
                default="all_nemo_users,all_new_users",
                help_text="Select which users this action applies to. You can select 'All NEMO users', 'All new users' (without NEMO accounts), and/or specific user types.",
            ),
        ),
        migrations.RenameModel(
            old_name="OnlineUserTraining",
            new_name="TrainingRecord",
        ),
        migrations.RenameField(
            model_name="trainingrecord",
            old_name="online_training",
            new_name="training",
        ),
        migrations.RenameModel(
            old_name="OnlineTrainingAction",
            new_name="Action",
        ),
        migrations.RenameField(
            model_name="action",
            old_name="online_training",
            new_name="training",
        ),
        migrations.RenameModel(
            old_name="OnlineTraining",
            new_name="Training",
        ),
    ]
