# Generated by Django 4.2.29 on 2026-05-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO_online_training", "0003_rename_online_training_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="traininguser",
            name="notes",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
