# Generated by Django 5.2.14 on 2026-05-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO_online_training", "0004_traininguser_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traininguser",
            name="notes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
