# Generated by Django 5.2.14 on 2026-08-12 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO_online_training", "0005_alter_traininguser_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="answer_key",
            field=models.JSONField(
                blank=True,
                help_text="JSON mapping of inputs to correct answers. Leave blank to only require completion.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="training",
            name="max_attempts",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Maximum allowed attempts. Set to 0 or leave blank for unlimited.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="training",
            name="passing_score_percentage",
            field=models.IntegerField(
                blank=True, help_text="Required score to pass (e.g. 80). Leave blank if no quiz is required.", null=True
            ),
        ),
        migrations.AddField(
            model_name="training",
            name="retry_cooldown_minutes",
            field=models.IntegerField(
                blank=True, default=0, help_text="Wait time in minutes between failed attempts.", null=True
            ),
        ),
        migrations.AddField(
            model_name="trainingrecord",
            name="failed",
            field=models.BooleanField(
                default=False, help_text="Indicates if the user has exhausted all attempts and failed."
            ),
        ),
        migrations.CreateModel(
            name="TrainingAttempt",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("score_percentage", models.FloatField(blank=True, null=True)),
                ("passed", models.BooleanField(default=False)),
                (
                    "responses",
                    models.JSONField(blank=True, help_text="The exact payload submitted by the user.", null=True),
                ),
                (
                    "training_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="NEMO_online_training.trainingrecord",
                    ),
                ),
            ],
        ),
    ]
