# Generated by Django 5.2.14 on 2026-08-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO_online_training", "0006_training_answer_key_training_max_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingrecord",
            name="cleared_for_retake",
            field=models.BooleanField(
                default=False, help_text="If True, the user is permitted to attempt this training again after failing."
            ),
        ),
    ]
